# Generated by Django 4.0.6 on 2022-07-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLdatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('series', models.CharField(max_length=300)),
                ('points', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
