# Generated by Django 4.0.6 on 2022-07-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLdatabase', '0002_driver_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='driver',
            name='series',
            field=models.CharField(max_length=3000),
        ),
    ]
