# Generated by Django 4.0.6 on 2022-07-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLdatabase', '0003_alter_driver_name_alter_driver_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
