# Generated by Django 4.0.6 on 2022-07-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLdatabase', '0004_driver_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='points',
            new_name='live_points',
        ),
        migrations.AddField(
            model_name='driver',
            name='min_points',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
