# Generated by Django 4.0.6 on 2022-10-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SLdatabase', '0005_rename_points_driver_live_points_driver_min_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='series',
        ),
        migrations.CreateModel(
            name='RacingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('series_name', models.CharField(max_length=40)),
                ('points', models.CharField(max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SLdatabase.driver')),
            ],
        ),
    ]
