# Generated by Django 4.0.6 on 2022-10-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLdatabase', '0007_alter_racingseries_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='racingseries',
            name='finish',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='racingseries',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='racingseries',
            name='year',
            field=models.IntegerField(),
        ),
    ]
